### ISSUE TITLE
安装之后怎么用啊？

### ISSUE THREAD

**Issue by alxdhuang** [996-icu-avengers/Natasha#11]

**Comment by lifenglsf** [comment]
同问

**Comment by lloydzhou** [comment]
这个插件是在你需要找工作的时候，搜索公司如果检查到属于996的公司就显示一个`996ICU`的标签。如果没有检查出来，就不会更改页面上的东西。

**Comment by alxdhuang** [comment]
> 这个插件是在你需要找工作的时候，搜索公司如果检查到属于996的公司就显示一个`996ICU`的标签。如果没有检查出来，就不会更改页面上的东西。

但是我在安装之后打开拉勾网没有发现任何标签啊。

<img width="969" alt="Screenshot 2019-04-16 at 11 34 46 PM" src="https://user-images.githubusercontent.com/48013855/56223482-6c542b00-60a0-11e9-9e1c-dd8a6cafbdb4.png">
