### ISSUE TITLE
安装之后看不到效果

### ISSUE THREAD

**Issue by lifenglsf** [996-icu-avengers/Natasha#16]
51job的效果
![image](https://user-images.githubusercontent.com/1817560/56198796-36964e80-606e-11e9-8abf-279376b4f9b4.png)
华为不是在996的列表清单吗？

**Comment by lloydzhou** [comment]
识别准确率需要提高

**Comment by lloydzhou** [comment]
#9

**Comment by lifenglsf** [comment]
现在怎么操作才能看到效果呢@lloydzhou
