### ISSUE TITLE
Boss直聘，宇宙条，支付宝这种加班狂魔未被标记

### ISSUE THREAD

**Issue by shevakuilin** [996-icu-avengers/Natasha#5]
https://www.zhipin.com/job_detail/?query=IOS&city=101010100&industry=&position=#/

**Comment by lloyd0408** [comment]
![image](https://user-images.githubusercontent.com/49503929/55934066-0a3f9400-5c62-11e9-84b7-7a16aafff90b.png)
![image](https://user-images.githubusercontent.com/49503929/55934076-10ce0b80-5c62-11e9-8ae0-e7fdc7a35567.png)

**Comment by lloyd0408** [comment]
#6
